name: DailyRewards
version: ${project.version}

authors: [Revivalo]
description: Reward system for players
website: https://discord.gg/TfUC8uJ

main: dev.revivalo.dailyrewards.DailyRewardsPlugin
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Oraxen
  - ItemsAdder

commands:
  reward:
    aliases: [rw]
  rewards:
    aliases: [rws]
  dreward:
    aliases: [dailyrewards]
  drewards:
