name: DailyRewards
version: 1.6.2
main: cz.revivalo.dailyrewards.DailyRewards
api-version: 1.13
softdepend: [PlaceholderAPI, Oraxen, ItemsAdder]
authors: [Revivalo]
description: Reward system for players
website: https://discord.gg/TfUC8uJ
commands:
  reward:
  rewards:
