name: DailyRewards
version: 1.3.0
main: cz.revivalo.dailyrewards.DailyRewards
api-version: 1.13
sofdepend: [PlaceholderAPI]
authors: [Revivalo]
description: Reward system for players
website: https://discord.gg/TfUC8uJ
commands:
  reward:
  rewards:
