name: DailyRewards
version: 1.6.7
main: dev.revivalo.dailyrewards.DailyRewardsPlugin
api-version: 1.13
softdepend: [PlaceholderAPI, Oraxen, ItemsAdder]
authors: [Revivalo]
description: Reward system for players
website: https://discord.gg/TfUC8uJ
commands:
  reward:
    aliases: [rw]
  rewards:
    aliases: [rws]
